### ISSUE TITLE
Add wheel files for arm64 architectures

### ISSUE THREAD

**Issue by jmottier-niryo** [michalc/stream-inflate#94]
### Issue Description
I am trying to install stream-inflate on an aarch64 (ARM64) architecture system (with Ubuntu server 24.04). However, I noticed that there are currently no pre-built wheel files available for this architecture.

The absence of wheel files requires the installation of build dependencies, such as `gcc-aarch64-linux-gnu`, `python3-dev` and `binutils` before installing the package with pip. This can complicate the installation process for users on ARM-based systems, and it force the users to install system-wide dependencies on the device.

### Request
Could you please consider adding pre-built wheel files for the aarch64 architecture? This would help improve the installation experience for users on ARM platforms.

**Comment by michalc** [comment]
Hi @jmottier-niryo,

Sounds good - and although I’ve not done this before suspect it shouldn’t be too tricky. The current wheels are built on GitHub actions, and I see they now have arm runners https://github.blog/changelog/2024-09-03-github-actions-arm64-linux-and-windows-runners-are-now-generally-available/, and also the manylinux project has arm-based Docker images that could be used to build the wheel files  https://github.com/pypa/manylinux.

Can’t give a precise ETA, but I suspect in the next few days if there are no unexpected problems

Michal

**Comment by michalc** [comment]
Ah a question just out of curiosity 
 - are you using this project directly, or via stream-unzip, or something else?

**Comment by michalc** [comment]
Now done! Released in v0.0.38
